# Generated by Django 5.0.7 on 2024-11-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
