# Generated by Django 5.0.7 on 2024-12-16 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Rating must be between 1 and 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
