version: "3.8"

services:
  db:
    image: postgres
    container_name: proximi_user_postgres
    environment:
      POSTGRES_USER: kubra
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pro_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
